base_submission=/tmp/potatojudge_submission
base_problem=/tmp/potatojudge_problems
base_workspace=/tmp/potatojudge

highly recommend put workspace under /tmp. This only work for sandbox. Will leave trash under it.
